[project]
name = "c-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "zaynab-3", email = "preset.rep@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.141.1",
]

[project.scripts]
c-backend = "c_backend:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
