"""add message processing state

Revision ID: 6c10c1e39bde
Revises: a376ae3ccdf0
Create Date: 2026-09-05 16:35:50.059836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c10c1e39bde'
down_revision: Union[str, Sequence[str], None] = 'a376ae3ccdf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('messages', sa.Column('outbound_external_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'outbound_external_id')
    op.drop_column('messages', 'processed_at')
    # ### end Alembic commands ###
