"""persist generated AI reply

Revision ID: cba3814f9172
Revises: 6c10c1e39bde
Create Date: 2026-09-05 18:32:13.269728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cba3814f9172'
down_revision: Union[str, Sequence[str], None] = '6c10c1e39bde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('generated_reply', sa.Text(), nullable=True))
    op.add_column('messages', sa.Column('ai_provider', sa.String(length=50), nullable=True))
    op.add_column('messages', sa.Column('ai_model', sa.String(length=255), nullable=True))
    op.add_column('messages', sa.Column('ai_generated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'ai_generated_at')
    op.drop_column('messages', 'ai_model')
    op.drop_column('messages', 'ai_provider')
    op.drop_column('messages', 'generated_reply')
    # ### end Alembic commands ###
